#!/bin/bash

#path of the to-do list file
todo_list="$HOME/.local/share/tdos/todos"

#variable to hold the value of the item to add when -n is used
new_item=""

#variable to hold the value of the search term
search=""

#retrieve conmmand line arguments. The ones expecting arguments are followed by ':'. https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/

while getopts "hn:is:c:" op; do
  #using case to match the option entered and call a corresponding function.
  case "${option}" in

    h)
      display_help() {
        echo "Welcome to the to-do list script. Here is how to use it:"
        echo "run the script with one of the following options:"
        echo "-h                show this message"
        echo "-n [itemname]     adds a new item to the list. subtitute [itemname] with your item."
        echo "-i                show all the tasks that are not completed"
        echo "-s [itemname]     search for a task. replace [itemname] with the task name."
        echo "-c [taskid]       mark a task completed. replace [taskid] with the id number."
      }
      ;;
    n)   
      add_item() {
        #save the command line argument to a variable to write to the to-do list. https://gitlab.com/cit2420/2420-notes-f24/-/blob/main/2420-notes/week-seven.md?ref_type=heads
        new_item=${OPTARG}
        line_count=wc -l $HOME/.local/share/tdos/todos | cut -d " " -f 1
      }
      ;;
    i)
      display_incomplete() {
        # search for text    https://help.ubuntu.com/community/grep
        grep "[[]]" "$todo_list"
      }
      ;;
    s)
      search_for_item() {
        #save the command line argument to a variable to use as a search term.
        search=${OPTARG}
        #grep, looking for the argument provided (stored in 'search')
        grep "$search" "$todo_list"
      }
      ;;
    c)
      mark_complete() {
        #save the command line argument to a variable to match with the id number.
        idnum=${OPTARG}
      }
  esac
  #check if no option was provided. Run display_all, printing entire file
  
  if [[ $1 == "" ]]; then
      cat "$todo_list" 
  fi

done

exit 0
